### PR TITLE
enhance CompositeArchRule.of

### PR DESCRIPTION
**Pull request by sullis**
- new method:  of(Collection)

### CODE REVIEW

**Comment by sullis** [comment]
WDYT? @codecholeric

**Comment by codecholeric** [comment]
Thanks a lot for the PR! :smiley: The only thing I'm wondering is: Wouldn't a single method that takes an `Iterable<ArchRule>` be sufficient? It would also swallow `Collection<ArchRule>` then. But I can't really imagine a scenario where one would only have  an `Iterator<ArchRule>` :thinking: That's not a type you usually really use, is it?

**Comment by sullis** [comment]
> Thanks a lot for the PR! 😃 The only thing I'm wondering is: Wouldn't a single method that takes an `Iterable<ArchRule>` be sufficient? It would also swallow `Collection<ArchRule>` then. But I can't really imagine a scenario where one would only have an `Iterator<ArchRule>` 🤔 That's not a type you usually really use, is it?

I removed of(Iterator).  I plan to use of(Collection) is one my internal projects.

**Comment by sullis** [comment]
@codecholeric WDYT?

**Comment by sullis** [comment]
@codecholeric  are there any plans to release a new version of ArchUnit?   (This PR was completed in July but there has not been any releases since May)

**Comment by sullis** [comment]
@codecholeric are there any plans to release a new version of ArchUnit? (This PR was completed in July 2020 but there have not been any releases since May 2020)

**Comment by codecholeric** [comment]
Yes, I know I'm super slow this time :disappointed: In short, yes, I'm waiting for a review on #484 and I want to implement the counter part of #428 to not have a difference between dependencies from self and to self. I actually planned to release this weekend, but didn't completely make it. Need to make sure to release quicker iterations in the future, this time the interval really is way too big :disappointed:

**Pull request merged**
