### PR TITLE
Support comments in archunit_ignore_patterns.txt

### PR DESCRIPTION
**Pull request by bedla**
Hi,
it would be nice to comment lines with description of ignored patterns. Pls take a look and say what do you think. Looks like that "# " is good enough :]
Thx 
Ivos

### CODE REVIEW

**Comment by codecholeric** [comment]
Wow, thanks for your next PR :smiley: 
Looks good to me, the only thing I'm wondering is if it's necessary to enforce that whitespace after # ?
I guess most people will add it anyway, but that the line suddenly doesn't count as comment anymore, if I write `#ignore that line` seems kind of surprising?

**Comment by hankem** [comment]
I'd also assume that `#` should be sufficient for a comment.

**Comment by bedla** [comment]
i have looked how regexp buddy solves comments and just copied it. no problem to change it ;]

**Comment by codecholeric** [comment]
Thanks for the adjustment! I've made a small change in the test, because I like consistency (even though, especially with Java 8, the AssertJ `assertThatThrownBy` approach is definitely nicer :wink:; with Java 7, cause of all the boilerplate, I have no strong opinion)
Also I've added this to the user guide.
Thanks a lot for contributing!! :smile:

**Comment by bedla** [comment]
thx for merge. i am happy to help :)

**Pull request merged**
