### PR TITLE
added beImmutable() to ArchConditions

### PR DESCRIPTION
**Pull request by bgalek**
Hello, I've made new assertion to check if class is immutable (no mutable fields). 
For me it would be useful. If You like it, please review my PR, I'm happy to update it if needed ;)

Feature wasn't discussed before so don't hesitate to decline the PR - I won't mind. 

It was fun making a contribution to this project, keep up the good work!
I hereby agree to the terms of the ArchUnit Contributor License Agreement.

### CODE REVIEW

**Comment by hankem** [comment]
Nice! But I'd probably change the wording from_beImmutable_ to, e.g., _haveOnlyFinalFields_.

**Comment by bgalek** [comment]
name changed accordingly to your comment ;)

**Comment by codecholeric** [comment]
Thanks for your PR!! I agree with @hankem, "immutable" would have been misleading, since a class can still heavily mutate its state (e.g. `final List<Object> list = new ArrayList<>()`).
But with the new rewording I like the addition, so I'll happily merge it :smiley:

**Comment by SteluHH** [comment]
I love this one. Comes in very handy especially for enforcement of immutability for `ValueObjects` in terms of Domain Driven Design. Thanks

**Comment by bgalek** [comment]
@SteluHH I'm glad that my contribution is appreciated! 😎 Keep up the good work :)

**Pull request merged**
