### PR TITLE
Add Predicate-based DescribedPredicate Factory

### PR DESCRIPTION
**Pull request by jzheaux**
Compose a DescribedPredicate from a Predicate and a description.

Signed-off-by: Josh Cummings <josh.cummings@gmail.com>

### CODE REVIEW

**Comment by jzheaux** [comment]
The error from Travis is:

```
Could not determine the dependencies of task ':archunit:shadowJar'.
> Could not resolve all dependencies for configuration ':archunit:runtimeClasspath'.
   > Could not resolve org.ow2.asm:asm:7.0.
     Required by:
         project :archunit
      > Could not resolve org.ow2.asm:asm:7.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm/7.0/asm-7.0.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/ow2/asm/asm/7.0/asm-7.0.pom'. Received status code 403 from server: Forbidden
   > Could not resolve org.slf4j:slf4j-api:1.7.25.
     Required by:
         project :archunit
      > Could not resolve org.slf4j:slf4j-api:1.7.25.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom'. Received status code 403 from server: Forbidden
```

It's not clear to me if there is something I should do to repair the PR? I followed the steps listed in [the contribution guildelines](https://github.com/TNG/ArchUnit/blob/master/CONTRIBUTING.md#how-to-contribute) and got a green light locally.

**Comment by codecholeric** [comment]
Thanks for your contribution :smile: I think the Travis CI was just broken somehow, I restarted the build and this time it passed.
I'm wondering if you're very attached to the name `when`? Because I think I myself would rather look for a factory method `DescribedPredicate.of(description, predicate)` if I look at the rest of the API. 
Or maybe `DescribedPredicate.test(description, predicate)`. 
`when` somehow doesn't trigger the association with a boolean predicate for me (rather reminds me of Mockito :wink:).
What do you think?

**Comment by jzheaux** [comment]
@codecholeric I see your point about `when`, though `of` seems a bit semantically weak since it could apply to several of the other factory methods as well.

What about `describe(description, predicate)`? It's kind of the inverse of your `test` proposal, focusing on a description being added to a test, as opposed to a test being added to a description.

**Comment by codecholeric** [comment]
I like `describe(description, predicate)` :smile: I've thought about it and it makes complete sense to me, because it adds a description to an existing predicate.
Do you want to make that renaming? Then I'll immediately merge it!

**Comment by jzheaux** [comment]
Excellent! I've updated the method name to `describe`, @codecholeric.

**Comment by codecholeric** [comment]
Okay, done, thanks a lot for the initiative and your contribution :smiley: I really appreciate it!

**Pull request merged**
