### PR TITLE
Add developer to published POMs

### PR DESCRIPTION
**Pull request by rweisleder**

### CODE REVIEW

**Comment by codecholeric** [comment]
Cool, welcome even more officially on board :sweat_smile: But seriously, thanks for your ongoing support over the months / years, I really appreciate it :smiley:
We should have an ArchUnit contributor meetup at some point, that would be awesome!!

**Comment by codecholeric** [comment]
Of course you missed ArchUnit `0.13.0` by 2 hours :rofl: 
But just in time for `1.0.0` :smile:

**Comment by rweisleder** [comment]
Thanks for merging this and that I can be part of ArchUnit!

>  We should have an ArchUnit contributor meetup at some point, that would be awesome!!

Maybe we meet someday at a conference, e.g. JavaLand or WJAX. :wink:

**Comment by codecholeric** [comment]
Thank **you** for your ongoing support! And yes, I had a little bit of time problems recently (and my main language switched to Kotlin :rofl:) so I haven't attended too many Java conferences in recent times, but who knows :wink:

**Pull request merged**
