### PR TITLE
Issue: #545 Feature Request: Classes that contain annotated methods

### PR DESCRIPTION
**Pull request by nils-christian**
Signed-off-by: Nils Christian Ehmke <nils@rhocas.de>

### CODE REVIEW

**Comment by codecholeric** [comment]
Hey, thank you so much for the PR, I really appreciate the support :smiley: 
I only think I didn't completely look at this from all angles, when I said I consider it fair to add this method. Somehow I looked at the predicate method you added to `JavaClass`, namely

```
containMethodsThatAre(DescribedPredicate<? super JavaMethod> predicate)
```

and I immediately thought "that method would be super flexible and cover it all". Since I had a super bad conscience that I told you "go for containMethodsThatAreAnnotatedWith(..) in the API" and now do a 180 and say "well, actually I like that more generic method better" I decided to give up my resolution about my current priorities and put in some effort here as well to make up for it.

So what I did is I pushed your new method `containMethodsThatAre(..)` through to the API and replaced the more specific `containMethodsthatAreAnnotatedWith(..)` method by that. I just had the feeling, with this method you could easily and concisely write

```
import static com.tngtech.archunit.core.domain.properties.CanBeAnnotated.Predicates.annotatedWith;
import static com.tngtech.archunit.lang.conditions.ArchPredicates.are;
---
classes().that().containAnyMethodsThat(are(annotatedWith(Deprecated.class)))
```

But at the same time nobody is going to ask "I want to filter classes that have a member of type X, why can I only check for annotations?" in two weeks. And also this way you can easily plug in `metaAnnotatedWith(..)` for example.

What do you think about this way to go? If you like it, you could squash my commit on top of yours. I thought about keeping the `containMembersAnnotatedWith(..)` method as well, but then decided against it, because it is pretty specific. And there are a lot of other methods of the same type that would be missing.
On the other hand with the current approach of `containAnyMethodsThat(predicate)`, you could even simply extend the syntax for `MethodsThat containAnyMethodsThat()` where you can use all the `MethodsThat` predicate methods again in a fluent way :thinking: 

Anyway, let me know what you think, if you like it we can simply squash it.

One thing I noticed though, we usually don't have any "Issue X" or similar in the commit messages. I typical follow the standard pattern of `if applied this commit will ${first_line_of_commit_message}`. So I would simply suggest something like

```
add `containAny{Members,Fields,Methods,...}That(..)` to rule syntax
```

**Comment by nils-christian** [comment]
Hi, 

I totally agree with your approach. A more generic version of the method seems like a good idea to me. I will open a new PR with the squashed commits. Thank you very much!

**Comment by hankem** [comment]
Just FYI: You could also have force-pushed your branch. 😉

**Comment by codecholeric** [comment]
@nils-christian oh yeah, sorry if I didn't make this explicit, you could have simply done some `git rebase -i`, squash my commit onto yours with a common message you think fits and then force push your branch :slightly_smiling_face:

**Pull request closed without merging**
